name: fastAPI
channels:
  - defaults
dependencies:
  - annotated-doc=0.0.4=py310hca03da5_0
  - annotated-types=0.6.0=py310hca03da5_1
  - anyio=4.10.0=py310hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - click=8.2.1=py310hca03da5_1
  - exceptiongroup=1.3.0=py310hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - fastapi=0.121.1=py310hf834670_0
  - h11=0.16.0=py310hca03da5_1
  - idna=3.11=py310hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - pydantic=2.12.4=py310hca03da5_0
  - pydantic-core=2.41.5=py310h931abed_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sniffio=1.3.1=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - starlette=0.47.3=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing-inspection=0.4.2=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - uvicorn=0.35.0=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/fastAPI
